package errorcodes

const (
	ERROR_ONLY_TWO_JUGS_ALLOWED          = "ERROR_0001"
	ERROR_MUST_PROVIDE_JUG_NAMES         = "ERROR_0002"
	ERROR_JUG_CAPACITY_MUST_GREATER_0    = "ERROR_0003"
	ERROR_MEASURE_MUST_GREATER_0         = "ERROR_0004"
	ERROR_MEASURE_MUST_LESS_MAX_CAPACITY = "ERROR_0005"
	ERROR_NO_SOLUTION                    = "ERROR_0006"
)